name: Publish

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

  workflow_dispatch: {}

jobs:
  json-schema-to-zod:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - run: npm install --frozen-lockfile
      - run: npm run build
      - run: npm run type:check
      - run: npm run test
      - name: Publish
        if: github.ref == 'refs/heads/master' || github.event_name == 'workflow_dispatch'
        uses: botpress/gh-actions/publish-if-not-exists@master
        with:
          path: "."
          token: "${{ secrets.NPM_ACCESS_TOKEN }}"
