name: Build, Test and Publish

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

  workflow_dispatch: {}

jobs:
  json-schema-to-zod:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
      - run: npm --version
      - run: node --version
      - run: npm run version
      - run: npm install --frozen-lockfile
      - run: npm run build
      - run: npm run type:check
      - run: npm run test
      - name: Publish on master
        if: github.ref == 'refs/heads/master' || github.event_name == 'workflow_dispatch'
        uses: botpress/gh-actions/publish-if-not-exists@master
        with:
          path: "."
          token: "${{ secrets.NPM_ACCESS_TOKEN }}"
